language: node_js

node_js:
  - 12.22.12
  - 10.24.1

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release

branches:
  only:
    - master
    - /^greenkeeper/.*$/
